// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
    DB: D1Database;
    BADGR_USERNAME: string;
    BADGR_PASSWORD: string;
}
